# Uncomment the next line to define a global platform for your project
  platform :ios, '13.0'

target 'anyRecApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'

  # Pods for anyRecApp

  target 'anyRecAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'anyRecAppUITests' do
    # Pods for testing
  end

end
